# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 296f102e7ffd304030466866ff22ae40be73ffbbbee143ae913b5c98d5b0eaf541f45bd424bf18d703b67534d756fe580180158c357b4b7d60a0e112396bf7bc

test:
  secret_key_base: 9b93c506c7474601557df2b0eac9356e37b9f4d130078d2f5ccb7ad14661a37789e5f812f9fdae4c99f52eb64a6cad5d7a7230df9725e623a001a4d36447d6af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
